### PR TITLE
Updated curve constructors

### PR DESCRIPTION
**Pull request by cppctamber**
Updated curve constructors
===
* Converted all curves constructors to classes
* Rearranged folders
* Removed math functions and put them in the `./math` folder
* Created `Tw2CurveKey`, `Tw2Curve` and `Tw2CurveSequencer` base classes
* Added `GetLength` and `Sort` prototypes to curves that were missing them (normalization)
* Added meta data to each curve constructors (see below)
* Fixed some bugs/ errors
* Fixed linting
* Fixed jsdocs
* Added operator enums to sequencers that use them

Curve Meta data
---
There are quite a few different curve geneoligies (legacy, maya, standard) and types (sequencer,curve), and their implementations aren't _quite_ the same.
I've added some curve constructor meta data which can be used to help figure out which can go with which, and is extremely handy if you are making a curve editor or are making any ccpwgl property animatable :3

*Curves Only*
* Key - The curve's key (there can be only one)

*Curves and Sequencers*
* curveType - {String} The type of curve/ sequencer (Curve Standard, Curve Legacy, Curve Maya, Sequencer Legacy, Sequencer Standard)
* inputDimension - {Number} The constructors child(ren) value dimension
* outputDimension - {Number} The constructors value dimension
* valueProperty - {String} The current value property name (`value`, `currentValue`, `eulerValue`... etc)

*Sequencers only*
* childProperties - {Array.<String>} An array of each curve property name (Standard Sequencers only)
* curveArray - {String} All child curves are found in a single array, this is it's name (Legacy Sequencers only)

Issues
---
* Did not modify `Tw2WbgTrack` which doesn't seem to have ever worked, not sure what is supposed to be happening here
* Some property names could probably be normalized, but I do not have access to any `.red` files that use curves extensively so have left them as they are.

### CODE REVIEW

**Comment by filipppavlov** [comment]
The reason for the mess with all curve types is that in the original eve client code we have (had) a few generations of curve systems. I did a cleaning pass on them in the client code quite some time ago, so now we have a single system for curves in the client.
Whenever I update ccpwgl next time I will change js curves to match the client ones. This will reduce the number of curve classes quite a bit.

**Comment by cppctamber** [comment]
I gathered as much - the enums originally showed this `CURVE_LEGACY` and `SEQUENCER_LEGACY` but I wasn't 100% sure. Perhaps rather than removing some of the old ones we can make a legacy directory and stick them all in there?

**Comment by filipppavlov** [comment]
Well, eventually those old .red files will become incompatible with new versions, not only because of curves. Probably a more stable although quite a bit more painful approach would be to convert those old files to new types if possible.

**Comment by cppctamber** [comment]
There are better things to spend your free time on, I think we just accept
that older models get deprecated and leave it at that.

**Pull request merged**
