### PR TITLE
Update ccpwgl.js

### PR DESCRIPTION
**Pull request by cppctamber**
Added functions for modifying a scene's environmental and star maps.
Added a function that returns the values of a tw2vectoreffect parameter

### CODE REVIEW

**Comment by Regner** [comment]
Again just a note about the commit and PR titles, please try and make them a little more descriptive in the future.

Appreciate the comments for everything you added though.

Will poke some people later to see what they think of the changes, looks good to me.

**Comment by cppctamber** [comment]
Yep will do, just being a noob.

**Comment by filipppavlov** [comment]
I have a few issues with this request.
The ccpwgl.getParameter function is not completely correct: the parameter may have no constantBuffer array attached, but still be a valid parameter (this is a rare case, but it does happen with some models). Regardless, it seems like it would be better to have a getter function on parameter object itself to get its value. Now that we have a build step for ccpwgl_int it should be easier for you to add it there. For completeness it needs to be on all Tw2...Parameter classes. I know effect parameters are a mess right now, but I never had time to clean the code up there.
The Scene.setEnvBlur function logs an error, which is inconsistent compared to Scene.setEnvReflection and Scene.setEnvCube.
Now about Scene.setEnvironment: shouldn't it set the background texture as well?

**Comment by cppctamber** [comment]
I'll remove this request for now - the setEnvironment doesn't include the background texture intentionally, as the user may want a different environment reflected on objects than this background. ie. a scene with a solid background doesn't have reflection maps, and looks better with them. The alternative of course is loading a nebula, and then disabling nebula rendering.

**Pull request closed without merging**
