### PR TITLE
Updated files in eve folder, minor changes to others

### PR DESCRIPTION
**Pull request by cppctamber**
src/eve
---
- Created new folders, and put relevant files in them
- Created `EveObject`, `EveChild`, `EveItem`, `EveSet` and `EveSetItem` base classes
- Converted `child`, `effect` and `object` folder files to classes/es6 and fixed linting
- Converted `EveSpaceScene` to es6
- Skipped converting `EveSOF` as my version is vastly different
- Skipped `item` folder as `EveBoosterSetItem` failed testing
- Moved `EveMissileWarhead` into the `EveMissile` folder
- Fixed minor error in `EveMissile`
- Added unique ids to objects. Defaults to using object ids, but UUIDs can be enabled with `store.Register({ uuid: true })`
- Cleaned up per line perObjectData declarations (See below changes)
- Changed the `Update` method argument order for some classes so they're now the same as others, ie. `EveChild.prototype.Update(dt, parentTransform)` rather than the reverse.
- Added `KeepAlive` method to `EveSpaceScene` so all of a scenes resources can be kept alive manually (helpful when you have multiple scenes)
- Removed references to environment related store variables in `EveSpaceScene` and replaced with per frame updates (helpful when you have multiple scenes)
- Added visibility controls for environment maps in `EveSpaceScene`
- Cleaned up the methods for setting environment maps in `EveSpaceScene`
- Moved all registrations of `Tw2VariableStore` variables to a single place (`src/index.js`)

src/core
---
- `Tw2VariableStore` has new properties and methods.
- `Tw2VariableStore` instantiation name has been renamed to `store`. 
- Refactored all uses of `variableStore._variables[name]` to `store.GetVariable(name)`
- Refactored variable registration methods to use a single method `RegisterVariable` which can handle all three variations and a new one `store.RegisterVariable(name:string, value:*, Type:string|Function)`
- `Tw2VariableStore` now stores Types, and all Parameters/ Types are registered with `Tw2VariableStore.RegisterType(name:string, Constructor:Class`). Custom user Types should also use this method.
- Types can be retrieved/ created by 'value' (if they have an `is` static method), or 'type' as a string or 'Type' as a Constructor. This will be useful for the `autoRegister` parameter in `Tw2Effect` when they are added :3
- Added 'is' static method to parameters to help identify values that are valid inputs for them. When using `Tw2VariableStore.GetType(name)` the first Type that returns true will be returned.
- All global variables are now defined in one place in the main 'index.js' file
- `Tw2VariableStore` Variables can now only be defined once, if you try to register it again the original will be returned. 
- Created `data` folder, and put all per object data methods in it and converted them to classes
- `EveBasicPerObjectData` now extends from `Tw2PerObjectData` although I'm not sure why there isn't just one of them that has vertex, pixel and fixed function declarations?
- `Tw2PerObjectData`, `Tw2RawData` and `EveBasicPerObjectData` can now take an object for declarations as an instantiation argument (ie. `let ffeData = new Tw2PerObjectData(perObjectDataDecl)`), rather than having to type out each declaration line by line
- `Tw2VertexElement` can now take declarations as an instantiation argument (an array of arrays, or an array of objects) so that you don't have to type out each declaration line by line (ie. `let vDecl = new Tw2VertexElement(vertexDecl)`)
- Renamed `Tw2VertexElement` enums and put them into an object

src/particle
---
- Added object ids to base classes

src/curves
---
- Added object ids to base classes

src/math
---
- Added ccpwgl_int compatible mat4 lookAt method `mat4.lookAtGL`
- Added ccpwgl_int compatible mat4 perspective methods `mat4.perspectiveGL`
- Added `vec3.project` and `vec3.unproject`
- Moved `EveCurveSetLineItem` methods to vec3 library
- Added some other minor mat4 helper methods
- Added `util` file which contains methods the library uses elsewhere multiple times (haven't removed the duplicates yet)
- Added two ID generation methods (`util.generateUUID` by three.js and `util.generateObjectID`) which are used for upcoming intersection, serialization and search methods.
- Added `util.generateID` method which uses `util.generateObjectID` by default, but can be changed to `util.generateUUID` with `store.Register({ uuid: true })`
- probably some other stuff(tm)

### CODE REVIEW

**Comment by cppctamber** [comment]
I've already converted the `/core/` folder but have to confirm source of errors in my refactored `eve/item/` folder before I can push it.

**Comment by cppctamber** [comment]
Also, do you mind if I move all the `extensions`, `paths`, `contructors`, and a new `dynamicResources` ojeccts into `Tw2VariableStore` rather than the `Tw2ResMan`? It will help with dependencies and detaching the `resMan` from a specific ccpwgl instantiation (ie. for people like  @Robbilie who have multiple ccpwgl_ints, and for myself when using a webworker based resMan).

**Comment by Regner** [comment]
Might be better to break PRs like this down into smaller ones. This PR is almost impossible to review.

**Comment by Robbilie** [comment]
that is quite a PR :D

**Comment by cppctamber** [comment]
Its mostly cosmetic, don't want to burn fillipp out too quickly :3

**Comment by cppctamber** [comment]
@filipppavlov I'll break this down into seperate pull requests to make it easier to review

**Pull request closed without merging**
