### PR TITLE
Added missing Enums to Tw2Device.js

### PR DESCRIPTION
**Pull request by cppctamber**
- Added missing enums for RS_BLENDOP & RS_BLENDOPALPHA
- source (CCP TELLUS + https://msdn.microsoft.com/en-us/library/windows/desktop/bb172509(v=vs.85).aspx )

### CODE REVIEW

**Comment by filipppavlov** [comment]
It's amazing it worked without those constants :) Can you please use them in Tw2Device.ApplyShadowState instead of hardcoded numbers.
Also if we'd want to use MIN/MAX blend states we need to check/enable EXT_blend_minmax extension.

**Comment by cppctamber** [comment]
> It's amazing it worked without those constants :) Can you please use them in Tw2Device.ApplyShadowState instead of hardcoded numbers.

Sorry not sure what you mean

**Comment by filipppavlov** [comment]
No, there's a piece of code there:
                if (this.alphaBlendState.states[this.RS_BLENDOP] == 2)
                {
                    blendOpAlpha = this.gl.FUNC_SUBTRACT;
                }
                else if (this.alphaBlendState.states[this.RS_BLENDOP] == 3)
                {
                    blendOpAlpha = this.gl.FUNC_REVERSE_SUBTRACT;
                }
where these constants are hardcoded

**Comment by cppctamber** [comment]
I've been trying to get scenes to work with transparent backgrounds, but alpha channels are always black when against the background. No matter what blend modes I tried I couldn't change this. Could it be related to this? I don't know too much about this part of the pipeline unfortunately

**Comment by filipppavlov** [comment]
There's no simple way to render things and have correct alpha channel. Our shaders output all kinds of crap into alpha when things are rendered with alpha blending disabled. 
If you need a correct alpha channel for the rendering one way to extract it is to use "blue screen matting" techniques. Possibly render the image several times against different backgrounds to extract transparency.

**Pull request merged**
