### PR TITLE
Add CurveLineSets to SpaceObjects

### PR DESCRIPTION
**Pull request by cppctamber**
Added per frame Update for curveLineSets
Added per frame Render for curveLineSets
Added per frame GetBatches for curveLineSets 
Added per frame UpdateViewDependentData for curveLineSets

### CODE REVIEW

**Comment by cppctamber** [comment]
The question of whether or not this is a valid change depends on whether `curveLineSets` are classed as a `children` or not (and as such should go in the `this.children` array). Because there are some core constructors missing which I am guessing go in `this.children` (such as EveOverlayEffect, GenericEffects and such) I am not able to 100% classify curveLineSets correctly and I don't know if adding curveLine sets to the children array will cause problems for compatibility.

**Comment by filipppavlov** [comment]
EveCurveLineSet is supposed to live as a top-level object in the scene.objects array.

**Comment by cppctamber** [comment]
I gathered as much, poor choice of words on my behalf. Could you perhaps define what `children` are in ccpwgl spaceObject terms? 

ie, An EveTransform (cursor.red for example) could contain multiple objects that _could_ also be top level objects, but they're combined together so that they can be treated as one object for simplicity.

**Comment by filipppavlov** [comment]
Children array is meant for EveTransform objects. But EveTransform can also happily live in scene.objects array. It all comes down to inheriting parent object's transform. As far as I remember, lines sets don't inherit it so they can't be used as children.
Also note that we are deprecating this "children" thing for space objects and EveTransform class in general. It is being replaced by a number of specialized objects. 
I haven't looked at it yet, but I'll probably be adding some of those with the next resource update.

**Comment by cppctamber** [comment]
Awesome thanks for the answer.
I am using curveLineSets that inherit from a parent object which is why it made sense (they have a method for this purpose) I'll keep this change in my version of ccpwgl and remove this pull request from here shortly.

**Pull request closed without merging**
